include:
  - path: ./storages.yaml

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    command: debugpy --listen 0.0.0.0:5678 -m main
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend
    restart: always
    depends_on:
      stashify-database:
        condition: service_healthy
    ports:
    - "5676:5678"

networks:
  backend:
    driver: bridge