include:
  - path: ./storages.yaml

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    command: python main.py
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend
    restart: always
    depends_on:
      stashify-database:
        condition: service_healthy

networks:
  backend:
    driver: bridge