from infrastructure.models.category import *  # noqa
from infrastructure.models.favorite import *  # noqa
from infrastructure.models.quiz import *  # noqa
from infrastructure.models.quiz_question import *  # noqa
from infrastructure.models.quiz_rating import *  # noqa
from infrastructure.models.quiz_result import *  # noqa
from infrastructure.models.resource_image import *  # noqa
from infrastructure.models.resource_item import *  # noqa
from infrastructure.models.resource_rating import *  # noqa
from infrastructure.models.user import *  # noqa
