from application.keyboards.base import BackToSearchResourcesKeyboardBuilderMixin
from application.keyboards.resources import ResourceItemKeyboardBuilder


class SearchResourceItemKeyboardBuilder(ResourceItemKeyboardBuilder, BackToSearchResourcesKeyboardBuilderMixin):
    pass
